### PR TITLE
Add on progress

### PR DESCRIPTION
**Pull request by hkhungit**
Hi guy.
I added a function progress in android and ios from your code. I hope you grant me a permission request to your project.

### CODE REVIEW

**Comment by FruitieX** [comment]
Hi, thanks for your pull request. Will try to review it during this week.

**Comment by ohtangza** [comment]
Any progress on this request?

**Comment by FruitieX** [comment]
Oops, thanks for the reminder. New ETA: end of this week!

**Comment by ohtangza** [comment]
Thanks for your response. I also have some plan to contribute to this project later. Cheers!

**Comment by davetao** [comment]
Any news on when this can be merged? It would be extremely useful

**Comment by FruitieX** [comment]
Huge apologies for taking so long on this, it's on me as I've been very busy with deadlines in several other projects. We have to find someone else to maintain this if my schedule continues like this. Sorry again!

**Comment by ohtangza** [comment]
Wow! Thanks for coming back, I am truly well using this repository (almost ready for production.)

**Pull request merged**
