### PR TITLE
fix ios rn 48+ && android acc record

### PR DESCRIPTION
**Pull request by zhangjunhou**

### CODE REVIEW

**Comment by FruitieX** [comment]
Hi, can you rebase this off of latest master where the RN 0.48 fix is already in? :)

(Fixed in https://github.com/futurice/react-native-audio-toolkit/pull/60)

**Comment by grimpmaster** [comment]
looks like tarball does not match current code base the override is still there.


    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

**Comment by zhangjunhou** [comment]
OK @FruitieX

**Comment by FruitieX** [comment]
Thanks!

**Pull request merged**
